management.endpoint.mappings.enabled=true
management.endpoints.web.exposure.include=info, health, mappings
spring.main.allow-circular-references=true
server.port=9900

logging.level.org.apache.cxf=TRACE
logging.level.org.apache.camel.component.cxf=TRACE
logging.level.javax.xml.stream=TRACE
logging.level.com.ctc.wstx=TRACE